### PR TITLE
Give a better error message when the markdown is of the wrong type

### PR DESCRIPTION
**Pull request by MaxGabriel**
I think this error message would have made #12 much easier to diagnose/debug.

### CODE REVIEW

**Comment by Tarrasch** [comment]
Did built for you locally right? Seems like I can't count on the Travis build for this.

**Comment by MaxGabriel** [comment]
This did build for me locally, but I can investigate and fix the Travis errors if you'd like over the coming days.

**Comment by Tarrasch** [comment]
I would much appreciate that @MaxGabriel! I already started barking up https://github.com/haskell/directory/issues/30 yesterday, I think it might be related. They already fixed it though, so lets see if Travis builds now or not :)

**Comment by Tarrasch** [comment]
Yea it seems it got auto-magically fixed: https://travis-ci.org/Tarrasch/yesod-text-markdown/builds/75708324

**Pull request merged**
